# Generated by Django 3.1 on 2020-08-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickets",
            name="booking_time",
            field=models.TimeField(auto_now=True),
        ),
    ]
